apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30500
        hostPort: 30500
    extraMounts:
      - hostPath: /tmp/fluent-bit-test
        containerPath: /tmp/fluent-bit-test
